# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160220_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
