# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 18:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('version', models.IntegerField(validators=[django.core.validators.MinValueValidator(5)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
