# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 21:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_tor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tor',
            options={'ordering': ['-version']},
        ),
        migrations.AlterField(
            model_name='tor',
            name='version',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
