# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_squashed_0008_ticket_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(upload_to=tickets.models.upload_path_generator),
        ),
    ]
