# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160311_2141'),
        ('tickets', '0002_auto_20160311_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='tor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.TOR'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
    ]
